### ISSUE TITLE
Issue to include generator-jest in my own generator

### ISSUE THREAD

**Issue by jbaris** [SBoudrias/generator-jest#67]
I am using this:
```    
    this.composeWith(require.resolve('generator-jest/generators/app'), {
      testEnvironment: 'node',
      coveralls: false
    });

    this.composeWith('generator-jest/generators/test', {
      filepath: 'controllers/weather.controller.js',
      componentName: 'WeatherController'
    });    
```
I am getting this error when running my own generator:
```
Error: Did not provide required argument filepath!
    at /home/juan/works/generate-node-service/node_modules/generator-jest/node_modules/yeoman-generator/lib/index.js:375:11
    at Array.forEach (<anonymous>)
    at module.exports.checkRequiredArgs (/home/juan/works/generate-node-service/node_modules/generator-jest/node_modules/yeoman-generator/lib/index.js:369:21)
    at module.exports.parseOptions (/home/juan/works/generate-node-service/node_modules/generator-jest/node_modules/yeoman-generator/lib/index.js:354:10)
    at module.exports.argument (/home/juan/works/generate-node-service/node_modules/generator-jest/node_modules/yeoman-generator/lib/index.js:276:10)
    at new module.exports (/home/juan/works/generate-node-service/node_modules/generator-jest/generators/test/index.js:11:10)
    at Environment.instantiate (/home/juan/npm/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:673:23)
    at instantiate (/home/juan/works/generate-node-service/node_modules/yeoman-generator/lib/index.js:550:23)
    at module.exports.composeWith (/home/juan/works/generate-node-service/node_modules/yeoman-generator/lib/index.js:579:33)
    at module.exports.default (/home/juan/works/generate-node-service/generators/app/index.js:260:10)

```
I am missing something?

**Comment by jbaris** [comment]
I found a the solution:
```
    this.composeWith('generator-jest/generators/test', {
      arguments: ['controllers/weather.controller.js'],
      componentName: 'WeatherController'
    });
```
